run:
  deadline: 5m
  tests: true

issues:
  exclude-dirs:
    - vendor/

linters:
  enable:
    - revive
    - govet
    - shadow
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unconvert
    - misspell
    - prealloc
    - gosec
  disable:
    - golint


linters-settings:
  errcheck:
    check-type-assertions: true
  gofmt:
    simplify: true
  gosec:
    excludes:
      - G104
  revive:
    severity: warning

