[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
donation_program = "BmNf7XjZZsy19oGcV4YaFvzRDmERo9PWhbUeabTvfzYE"

[programs.localnet]
donation_program = "BmNf7XjZZsy19oGcV4YaFvzRDmERo9PWhbUeabTvfzYE"

[programs.testnet]
donation_program = "DgZn9fZf9xyzWHGToXJjMUCVpNsmCqmk7XoWet1s7kwF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://solana-devnet.g.alchemy.com/v2/yvIHkRX3MHdGAONF_Zwzy_IRwj7dfqjo"
wallet = "~/.config/solana/id.json"
